# Generated by Django 2.2.2 on 2019-07-29 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_title', models.TextField(max_length=100)),
                ('project_id', models.IntegerField(primary_key=True, serialize=False)),
                ('project_description', models.TextField(max_length=300)),
            ],
            options={
                'ordering': ['project_id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('project_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='artgallery.Project')),
            ],
        ),
    ]
